Repository kubernetes-sigs/node-ipam-controller, pull requests merged in 2024-07, with the labels that each got.

#16 chore: update image to gcr.io/k8s-staging-node-ipam-controller and registry.k8s.io/node-ipam-controller.
  .github/workflows/e2e.yml
  Makefile
  README.md
  charts/node-ipam-controller/values.yaml
  cloudbuild.yaml
Labels: approved, lgtm, lifecycle/stale, cncf-cla: yes, size/M

#21 docs: add two more examples
  examples/clustercidr-different-ip-pools-for-same-node-group.yaml
  examples/clustercidr-different-node-groups.yaml
Labels: approved, size/L, lgtm, cncf-cla: yes

#24 Add validation for immutable fields.
  charts/node-ipam-controller/gen/crds/networking.x-k8s.io_clustercidrs.yaml
  pkg/apis/clustercidr/v1/types.go
  pkg/controller/ipam/ipam_test.go
Labels: approved, lgtm, cncf-cla: yes, size/M
