Repository kubernetes-sigs/node-ipam-controller, pull requests merged in 2024-08, with the labels that each got.

#20 feat: add leader-election option
  charts/node-ipam-controller/templates/_helpers.tpl
  charts/node-ipam-controller/templates/deployment.yaml
  charts/node-ipam-controller/templates/serviceaccount.yaml
  charts/node-ipam-controller/values.yaml
  main.go
  pkg/leaderelection/leaderelection.go
Labels: approved, size/L, lgtm, cncf-cla: yes

#30 Update image owner to k8s-staging-networking.
  .github/workflows/e2e.yml
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes

#28 handle nodes with PodCIDRs not matching any ClusterCIDR
  pkg/controller/ipam/multi_cidr_range_allocator.go
  pkg/controller/ipam/multi_cidr_range_allocator_test.go
Labels: kind/bug, approved, size/L, lgtm, cncf-cla: yes
